### ISSUE TITLE
Hide clock in WatchOS 6

### ISSUE THREAD

**Issue by richieshilton** [kuglee/TermiWatch#22]
Just loaded this for the first time onto watchOS 6 beta. Does the default top right clock usually hide? Is there a way to do this on WatchOS 6?

**Comment by p4rzival0ne** [comment]
same problem.. on my Series 5 with WatchOS 6 final

**Comment by Zhoki86** [comment]
+ I have a similar problem too, on my Series 4 with WatchOS 6.0.1

**Comment by SConaway** [comment]
Same as well here .

**Comment by billyjacoby** [comment]
seeing the same issue on a series 4 here

**Comment by Liqueseous** [comment]
Same on WatchOS 6.1 for Series 5

**Comment by jackhagen** [comment]
Same. WatchOS 6.1 Series 3. App is otherwise perfect.

**Comment by vikemosabe** [comment]
So, I haven’t had the chance to really look into this myself, but I took the liberty of shortening the first line so it doesn’t have text over text at least. 
[https://www.dropbox.com/s/pmz5z29fe0uvu4r/2019-11-24%2015.40.31.png?dl=0](https://www.dropbox.com/s/pmz5z29fe0uvu4r/2019-11-24%2015.40.31.png?dl=0)

**Comment by jackhagen** [comment]
U+1F919
Thanks!!

**Comment by kuglee** [comment]
I've added the fix for hiding the time.
