### ISSUE TITLE
Is there a way to customize user@watch?

### ISSUE THREAD

**Issue by jsonjordan** [kuglee/TermiWatch#24]
If I wanted to customize  the display to be `myname@watch` or something, is there a way I can do that?

**Comment by kuglee** [comment]
If you open the Interface.storyboard in TermiWatch WatchKit App in Xcode, you can edit the entire interface. 
![Képernyőfotó 2019-12-19 - 22 46 55](https://user-images.githubusercontent.com/1316211/71212374-7d99ab00-22b1-11ea-86e1-5e0a5757c4d0.png)

**Comment by jsonjordan** [comment]
I tried this, rebuilt the project, and then uninstalled and reinstalled the app on my watch, and it still shows user@

Thanks for the quick reply!

**Comment by TheTylerJP** [comment]
After you make the changes to interface.storyboard, delete the app from your Apple Watch, re-run through Xcode and re-install the Apple Watch app and it'll work! :)

**Comment by jsonjordan** [comment]
That worked!

Thanks a ton!

**Comment by TyJPhillips** [comment]
@jsonjordan you're welcome! You can close out the issue now! Happy coding 👍
