### ISSUE TITLE
Failed to Launch iOS 13, wOS 6.1, Xcode11

### ISSUE THREAD

**Issue by samwandosamtin** [kuglee/TermiWatch#31]
when building is almost finished this error occurs "
![Ekran Resmi 2020-03-24 04 39 24](https://user-images.githubusercontent.com/62579452/77379307-717a2980-6d89-11ea-971f-257f5613f506.png)
i followed the guide and touch nothing else.

**Comment by kuglee** [comment]
You could try these:
https://stackoverflow.com/questions/33178032/failed-to-launch-ibcocoatouchimagecatalogtool-via-coresimulator-spawn

**Comment by samwandosamtin** [comment]
Tried about 10 times. Doesn't work.

**Comment by samwandosamtin** [comment]
I solved. Unselect apple watch assets in AppIcon. This removes app icon for apple watch but it working now. Thanks for developing and sharing.
