### ISSUE TITLE
Does it support watchOS 7?

### ISSUE THREAD

**Issue by someBrown** [kuglee/TermiWatch#37]
When I opened it on watch, it crashed. **Xcode 11.6.** Do I need to download Xcode 12？

**Comment by DogBrown** [comment]
This may be the cause


func swizzleDefaultTime() {
  try! swizzleInstanceMethodObjcString(
    of: "CLKTimeFormatter",
    from: "timeText",
    to: #selector(CLKTimeFormatter.swizzled_timeText)
  )
}

Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Swizzle.SwizzleError.classNotFound(errorMessage: "Swizzled class \"CLKTimeFormatter\" could not be found!")

**Comment by kuglee** [comment]
It's not updated to wathOS 7 yet.

What happens if you comment the inside of the function?

**Comment by DogBrown** [comment]
> It's not updated to wathOS 7 yet.
> 
> What happens if you comment the inside of the function?

It will have this problem
Hide clock in WatchOS 6 #22

**Comment by kuglee** [comment]
Thanks for pointing this out. I'll take a look at it.

**Comment by kuglee** [comment]
In the mean time you should try changing line 63 in `InterfaceController.swift` from
`  if #available(watchOS 6, *) {` to `  if #available(watchOS 7, *) {

**Comment by DogBrown** [comment]
> In the mean time you should try changing line 63 in `InterfaceController.swift` from
> ` if #available(watchOS 6, *) {` to ` if #available(watchOS 7, *) {`

I tried, but after this function is called, there is an error

**Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Swizzle.SwizzleError.classNotFound(errorMessage: "Swizzled class "CLKTimeFormatter" could not be found!")**

func swizzleDefaultTime() {
try! swizzleInstanceMethodObjcString(
of: "CLKTimeFormatter",
from: "timeText",
to: #selector(CLKTimeFormatter.swizzled_timeText)
)
}

**Comment by kuglee** [comment]
Thanks. It seems like this needs further investigation

**Comment by DogBrown** [comment]
> Thanks. It seems like this needs further investigation.

Thanks.I like this watch face very much

**Comment by kuglee** [comment]
I've created a watchOS7 branch that has the fix for hiding the time. Unfortunately I can't try it on real hardware right now. Could you try it?

**Comment by tuliosilvajunior** [comment]
> I've created a watchOS7 branch that has the fix for hiding the time. Unfortunately I can't try it on real hardware right now. Could you try it?

I Can try it.

**Comment by tuliosilvajunior** [comment]
> I've created a watchOS7 branch that has the fix for hiding the time. Unfortunately I can't try it on real hardware right now. Could you try it?

Yeah! It's working perfectly!
Thanks!

**Comment by kuglee** [comment]
I've fixed the weather and the font issues. It's on the master branch.

**Comment by DogBrown** [comment]
> I've fixed the weather and the font issues. It's on the master branch.

 thanks，but the temperature still not working

**Comment by DogBrown** [comment]
> I've fixed the weather and the font issues. It's on the master branch.

And can you add sleep analysis?

**Comment by mika-ma** [comment]
This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thanks, mika.
