### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 4.2.1 compiler

### ISSUE THREAD

**Issue by maximdietz** [kuglee/TermiWatch#5]
No other errors, using the latest release I get an error on this line: 

`3 - import PMKCoreLocation`_Module compiled with Swift 5.0 cannot be imported by the Swift 4.2.1 compiler_

**Comment by kuglee** [comment]
Please download this version for Swift 4:
https://github.com/kuglee/TermiWatch/releases/download/1.1.1/TermiWatch_1.1.1.zip

**Comment by maximdietz** [comment]
Thanks, that worked perfectly.
