### ISSUE TITLE
Missing WatchKit Extension?

### ISSUE THREAD

**Issue by loox** [kuglee/TermiWatch#54]
When executing the menu > **Product** > **Run** phase, I get this error:

`error: WatchKit App doesn't contain any WatchKit Extensions whose WKAppBundleIdentifier matches "com.user.TermiWatch.watchkitapp". Verify that the value of WKAppBundleIdentifier in your WatchKit Extension's Info.plist matches the value of CFBundleIdentifier in your WatchKit App's Info.plist.
`
(Actual user name redacted)

**Comment by mertcb** [comment]
Hey, just change the WKAppBundleIdentifier value to "com.xxx.TermiWatch.watchkitapp" from "com.xxx.TermiWatch.watchkitapp" which you have changed at step 2, also you have to do that for watchkit app

**Comment by johanguse** [comment]
@loox try this step:

1 - Select Xcode menu -> Find -> Find and Replace in Project….
2 - In the Text field type kuglee.
3 - In the With field type the name of your developer account. (The name of your Apple ID without the @xxxx.com.)
4 - Click the Replace All button.

**Comment by loox** [comment]
Thanks to everyone for the advice! I could finally do it. :-)
